---

## Role to run functionnal tests on Sympa


- name: Install required CPAN Perl modules
  apt: name={{ item }} state=present
  tags: test
  with_items:
  - libtest-bdd-cucumber-perl # Cucumber-style acceptance testing framework in Perl
  - libwww-mechanize-perl # module to automate interaction with websites








