---

- name: "Install Sympa [1/3: configure]"
  shell: ./configure --prefix={{ sympa_install_prefix }} --with-lockdir=/var/lock --without-initdir --with-unitsdir=/lib/systemd/system
  args:
    chdir: "{{ sympa_install_prefix }}/src/{{ source_dir }}"
    executable: /bin/bash

- name: "Install Sympa [2/3: make]"
  shell: make
  args:
    chdir: "{{ sympa_install_prefix }}/src/{{ source_dir }}"
    executable: /bin/bash

- name: "Install Sympa [3/3: make install]"
  shell: make install
  args:
    chdir: "{{ sympa_install_prefix }}/src/{{ source_dir }}"
    executable: /bin/bash

