---

-name: Ensures git is installed.
  apt:
    name: git
    state: present

- name: Download sources from repository
  git:
    repo: "{{ sympa_repository }}"
    dest: "{{ sympa_install_prefix }}/src/{{ source_dir }}"
    force: yes
    version: "{{ sympa_repository_version }}"

- name: Prepare configure
  shell: autoreconf -i
  args:
    chdir: "{{ sympa_install_prefix }}/src/{{ source_dir }}"
    executable: /bin/bash

