---
- name: Install Sympa configuration file
  template: src=sympa.conf.j2 dest=/etc/sympa/sympa.conf owner=sympa group=sympa mode=0640
  tags: sympa_conf
  notify: restart sympa
  
- name: Create sympa log file
  file: dest=/var/log/sympa state=touch mode=622 owner=syslog group=adm
  tags: syslog
  
- name: Install custom rsyslog conf file
  template: src=rsyslog/sympa.conf.j2 dest=/etc/rsyslog.d/sympa.conf mode=0644
  tags: syslog
  notify: restart rsyslog

- name: Configure logrotate
  template: src=logrotate/sympa.j2 dest=/etc/logrotate.d/sympa mode=0644
  tags: logrotate
  
