---

- name: Install prerequisites for Sympa
  tags: sympa_prereq
  import_tasks: sympa_prereq.yml
  
- name: Getting source folder name
  tags: always
  include_vars: source_dir_repo.yml
  when: sympa_install_from_repository
  
- name: Getting source folder name
  tags: always
  include_vars: source_dir_tgz.yml
  when: not sympa_install_from_repository

- name: Download Sympa sources
  tags: sympa_install
  import_tasks: sympa_install/get_sources.yml

- name: Install Sympa software
  tags: sympa_install, reinstall
  import_tasks: sympa_install/deploy.yml

- name: Sympa post-install operations
  tags: sympa_install
  import_tasks: sympa_install/post_install.yml

- name: Configure postfix and mail aliases
  tags: sympa_mail
  import_tasks: sympa_mail.yml

- name: Configure Apache
  tags: sympa_web
  import_tasks: sympa_web.yml

- name: Install and configure database
  tags: sympa_db
  import_tasks: sympa_db.yml

- name: Enable Sympa startup
  tags: sympa_startup
  import_tasks: sympa_startup.yml

## include_vars merges all variables in a single hash
## therefore each robot YML file needs to have a different hash key
- include_vars:
    dir: "{{ inventory_dir }}/sympa_virtual_robots"
    name: robots
  tags: sympa_robots

#- name: Dump variables définissant les robots
#  debug:
#    var: "{{ item.value }}"
#    verbosity: 0
#  with_dict: "{{ robots }}"
#  tags: sympa_robots

## Here we use loop_var to prevent conflicts on item var name with outer loops
- name: Install and configure Sympa virtual robots
  tags: sympa_robots
  include_role:
    name: sympa_virtual_robot
  vars:
    robot: "{{ robot_item.value }}"
  with_dict: "{{ robots }}"
  loop_control:
    loop_var: robot_item
 
 # Include environment specific tasks
- include: "{{ inventory_dir }}/tasks/sympa.yml"
