---
# Configure postfix and mail aliases

- name: Install required packages
  apt: name={{ item }} state=present
  with_items:
    - postfix

- name: Install Postfix main.cf configuration file
  template: src=postfix/main.cf.j2 dest=/etc/postfix/main.cf
  notify: restart postfix
  
- name: Create required /etc/mail/ directory    
  file: dest=/etc/mail state=directory mode=755 owner=sympa group=sympa

- name: Check if /etc/mail/sympa_list_aliases file exists
  stat:
    path: /etc/mail/sympa_list_aliases
  register: sympa_list_aliases_check 

- name: Install Sympa default list mail aliases
  template: src=postfix/sympa_list_aliases.j2 dest=/etc/mail/sympa_list_aliases owner=sympa group=sympa mode=0664 force=no
  when: sympa_list_aliases_check.stat.exists == False
  notify: update postfix aliases database

- name: Create virtual alias maps
  template:
    src: postfix/postfix_virtual.j2
    dest: /etc/postfix/virtual

- name: Compile virtual alias maps
  shell: postmap /etc/postfix/virtual

- name: Creating sympa global alias
  template:
    src: postfix/sympa_global_aliases.j2
    dest: /etc/mail/sympa_global_aliases
  notify: update postfix aliases database

- name: Compile bounce alias
  shell: postalias /etc/mail/sympa_global_aliases
